#!/bin/bash
wmctrl -x -a "crx__pkooggnaalmfkidjmlhoelhdllpphaga.Microsoft-edge" || /opt/microsoft/msedge/microsoft-edge --profile-directory=Default --app-id=pkooggnaalmfkidjmlhoelhdllpphaga --app-url=https://outlook.office365.com/mail/
