#!/bin/bash
wmctrl -x -a "crx__cifhbcnohmdccbgoicgdjpfamggdegmo.Microsoft-edge" || /opt/microsoft/msedge/microsoft-edge --profile-directory=Default --app-id=cifhbcnohmdccbgoicgdjpfamggdegmo --app-url=https://teams.microsoft.com/v2/?clientType=pwa
