#!/bin/bash

PATH=$HOME/bin/:$PATH
PATH=$HOME/.local/bin:$PATH
export PATH

export GOPATH=~/src/go

export PATH="$HOME/bin/${PATH:+:$PATH}"
export PATH="$HOME/.local/bin${PATH:+:$PATH}"
export PATH="$HOME/opt/node/bin${PATH:+:$PATH}"
export COLORTERM=truecolor

export PKG_CONFIG_PATH=${PKG_CONFIG_PATH:+$PKG_CONFIG_PATH:}$HOME/lib/pkgconfig/:$HOME/lib64/pkgconfig
export LIBRARY_PATH=${LIBRARY_PATH:+$LIBRARY_PATH:}$HOME/lib/:$HOME/lib64/
export CPATH=${CPATH:+$CPATH:}$HOME/include/
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$HOME/lib/:$HOME/lib64/

